### PR TITLE
Ask for camera permission

### PR DESCRIPTION
**Pull request by bryant1410**

### CODE REVIEW

**Comment by VictorAlbertos** [comment]
Hi @bryant1410 

As far as I know, there is no need to request permissions to access the built-in camera. So, I don't know why this permission should be required. 

Can you please explain it?

**Comment by bryant1410** [comment]
A Nexus 5X crashed because it didn't have CAMERA permission.

**Comment by VictorAlbertos** [comment]
Digging a little more about this issue, I've found this [post](http://stackoverflow.com/questions/7546695/camera-working-without-camera-permission) on stack. 

But it seems to be not good documented at all. Does the device open the camera, or instead it opens another application which uses the camera?

**Comment by bryant1410** [comment]
When it works, it opens the camera, yes, not other app.

**Comment by bryant1410** [comment]
I know I did a quick-and-dirty solution, but on the other hand I didn't wanted to ask for camera permission if the user wanted to go to the gallery.

**Comment by VictorAlbertos** [comment]
In this [link](https://developer.android.com/training/camera/photobasics.html)  taken from android developer official site, there is an example about how to take a photo using camera. And there is no permissions registered.

What I think could be the problem is that your device has not any app to handle the intent, and for that reason the app crashes. I'm going to investigate a little more about this error, in order to handle the error derived from this scenario.

**Comment by bryant1410** [comment]
But the error was `SecurityException` and was about permissions, not that I didn't have an app to handle the intent. This occured after I revoked camera permission to the app (Android 6.0).

**Comment by bryant1410** [comment]
btw, in that link, it does ask for permission in the manifest. I think it doesn't ask for dynamic permissions because it's outdated.

**Comment by VictorAlbertos** [comment]
I'm going to accept the pull request, but I'm going to refactor some code too.

**Comment by bryant1410** [comment]
Sounds good :+1:

**Comment by VictorAlbertos** [comment]
Thanks again for the contribution :)
The [last release 0.0.9](https://github.com/FuckBoilerplate/RxPaparazzo/releases/tag/0.0.9) contains these changes.

**Pull request merged**
